/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef PLAT_SENSOR_TABLE_H
#define PLAT_SENSOR_TABLE_H

#include <stdint.h>
#include "sensor.h"

#define TMP75_TEMP_ADDR (0x94 >> 1)
#define INA233_E1S_0_ADDR (0x8c >> 1)
#define INA233_E1S_1_ADDR (0x88 >> 1)
#define INA233_E1S_2_ADDR (0x98 >> 1)
#define INA233_MAIN_ADDR (0x90 >> 1)

#define TMP75_TEMP_OFFSET 0x00
#define INA233_VOLT_OFFSET 0x8B
#define INA233_CURR_OFFSET 0x8C
#define INA233_PWR_OFFSET 0x96

enum SENSOR_NUM {

	//1OU
	SENSOR_NUM_1OU_TEMP = 0x01,

	SENSOR_NUM_1OU_E1S_SSD0_P12V_VOLT_V,
	SENSOR_NUM_1OU_E1S_SSD1_P12V_VOLT_V,
	SENSOR_NUM_1OU_E1S_SSD2_P12V_VOLT_V,
	SENSOR_NUM_1OU_P12V_VOLT_V,

	SENSOR_NUM_1OU_E1S_SSD0_P3V3_ADC_VOLT_V,
	SENSOR_NUM_1OU_E1S_SSD1_P3V3_ADC_VOLT_V,
	SENSOR_NUM_1OU_E1S_SSD2_P3V3_ADC_VOLT_V,

	SENSOR_NUM_1OU_P3V3_STBY_ADC_VOLT_V,
	SENSOR_NUM_1OU_P1V8_ADC_VOLT_V,
	SENSOR_NUM_1OU_P0V9_ADC_VOLT_V,
	SENSOR_NUM_1OU_P1V2_ADC_VOLT_V,

	SENSOR_NUM_1OU_E1S_SSD0_P12V_CURR_A,
	SENSOR_NUM_1OU_E1S_SSD1_P12V_CURR,
	SENSOR_NUM_1OU_E1S_SSD2_P12V_CURR,
	SENSOR_NUM_1OU_P12V_CURR_A,

	SENSOR_NUM_1OU_E1S_SSD0_P12V_PWR_W,
	SENSOR_NUM_1OU_E1S_SSD1_P12V_PWR,
	SENSOR_NUM_1OU_E1S_SSD2_P12V_PWR,
	SENSOR_NUM_1OU_P12V_PWR_W,

	//3OU
	SENSOR_NUM_3OU_TEMP,

	SENSOR_NUM_3OU_E1S_SSD0_P12V_VOLT_V,
	SENSOR_NUM_3OU_E1S_SSD1_P12V_VOLT_V,
	SENSOR_NUM_3OU_E1S_SSD2_P12V_VOLT_V,
	SENSOR_NUM_3OU_P12V_VOLT_V,

	SENSOR_NUM_3OU_E1S_SSD0_P3V3_ADC_VOLT_V,
	SENSOR_NUM_3OU_E1S_SSD1_P3V3_ADC_VOLT_V,
	SENSOR_NUM_3OU_E1S_SSD2_P3V3_ADC_VOLT_V,

	SENSOR_NUM_3OU_P3V3_STBY_ADC_VOLT_V,
	SENSOR_NUM_3OU_P1V8_ADC_VOLT_V,
	SENSOR_NUM_3OU_P0V9_ADC_VOLT_V,
	SENSOR_NUM_3OU_P1V2_ADC_VOLT_V,

	SENSOR_NUM_3OU_E1S_SSD0_P12V_CURR_A,
	SENSOR_NUM_3OU_E1S_SSD1_P12V_CURR,
	SENSOR_NUM_3OU_E1S_SSD2_P12V_CURR,
	SENSOR_NUM_3OU_P12V_CURR_A,

	SENSOR_NUM_3OU_E1S_SSD0_P12V_PWR_W,
	SENSOR_NUM_3OU_E1S_SSD1_P12V_PWR,
	SENSOR_NUM_3OU_E1S_SSD2_P12V_PWR,
	SENSOR_NUM_3OU_P12V_PWR_W
};

void load_sensor_config(void);

#endif
