/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
#include <string.h>

#include "ast_adc.h"
#include "sensor.h"

#include "plat_i2c.h"
#include "plat_sensor_table.h"
#include "plat_hook.h"

sensor_cfg plat_1OU_sensor_config[] = {
	/*  number,
        type,
        port,
        address,
        offset,
        access check,
        arg0,
        arg1,
        sample_count,
        cache,
        cache_status,
        mux_ADDRess,
        mux_offset,
        pre_sensor_read_fn,
        pre_sensor_read_args,
        post_sensor_read_fn,
        post_sensor_read_args
    */

	{ SENSOR_NUM_1OU_TEMP, sensor_dev_tmp75, I2C_BUS4, TMP75_TEMP_ADDR, TMP75_TEMP_OFFSET,
	  stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0,
	  SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL, NULL },

	//adc
	{ SENSOR_NUM_1OU_P3V3_STBY_ADC_VOLT_V, sensor_dev_ast_adc, ADC_PORT0, NONE, NONE,
	  stby_access, 2, 1, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0,
	  SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL, &adc_asd_init_args[0] },

	{ SENSOR_NUM_1OU_E1S_SSD0_P3V3_ADC_VOLT_V, sensor_dev_ast_adc, ADC_PORT1, NONE, NONE,
	  dc_access, 2, 1, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0,
	  SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL, &adc_asd_init_args[0] },

	{ SENSOR_NUM_1OU_E1S_SSD1_P3V3_ADC_VOLT_V, sensor_dev_ast_adc, ADC_PORT2, NONE, NONE,
	  dc_access, 2, 1, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0,
	  SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL, &adc_asd_init_args[0] },

	{ SENSOR_NUM_1OU_E1S_SSD2_P3V3_ADC_VOLT_V, sensor_dev_ast_adc, ADC_PORT3, NONE, NONE,
	  dc_access, 2, 1, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0,
	  SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL, &adc_asd_init_args[0] },

	{ SENSOR_NUM_1OU_P1V8_ADC_VOLT_V, sensor_dev_ast_adc, ADC_PORT4, NONE, NONE, dc_access, 1,
	  1, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS,
	  NULL, NULL, NULL, NULL, &adc_asd_init_args[0] },

	{ SENSOR_NUM_1OU_P0V9_ADC_VOLT_V, sensor_dev_ast_adc, ADC_PORT5, NONE, NONE, dc_access, 1,
	  1, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS,
	  NULL, NULL, NULL, NULL, &adc_asd_init_args[0] },

	{ SENSOR_NUM_1OU_P1V2_ADC_VOLT_V, sensor_dev_ast_adc, ADC_PORT6, NONE, NONE, dc_access, 1,
	  1, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS,
	  NULL, NULL, NULL, NULL, &adc_asd_init_args[0] },

	//INA233 VOL
	{ SENSOR_NUM_1OU_E1S_SSD0_P12V_VOLT_V, sensor_dev_ina233, I2C_BUS3, INA233_E1S_0_ADDR,
	  INA233_VOLT_OFFSET, dc_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL,
	  &ina233_init_args[0] },

	{ SENSOR_NUM_1OU_E1S_SSD1_P12V_VOLT_V, sensor_dev_ina233, I2C_BUS3, INA233_E1S_1_ADDR,
	  INA233_VOLT_OFFSET, dc_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL,
	  &ina233_init_args[0] },

	{ SENSOR_NUM_1OU_E1S_SSD2_P12V_VOLT_V, sensor_dev_ina233, I2C_BUS3, INA233_E1S_2_ADDR,
	  INA233_VOLT_OFFSET, dc_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL,
	  &ina233_init_args[0] },

	{ SENSOR_NUM_1OU_P12V_VOLT_V, sensor_dev_ina233, I2C_BUS3, INA233_MAIN_ADDR,
	  INA233_VOLT_OFFSET, dc_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL,
	  &ina233_init_args[0] },

	//INA233 CURR
	{ SENSOR_NUM_1OU_E1S_SSD0_P12V_CURR_A, sensor_dev_ina233, I2C_BUS3, INA233_E1S_0_ADDR,
	  INA233_CURR_OFFSET, dc_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL,
	  &ina233_init_args[0] },

	{ SENSOR_NUM_1OU_E1S_SSD1_P12V_CURR, sensor_dev_ina233, I2C_BUS3, INA233_E1S_1_ADDR,
	  INA233_CURR_OFFSET, dc_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL,
	  &ina233_init_args[0] },

	{ SENSOR_NUM_1OU_E1S_SSD2_P12V_CURR, sensor_dev_ina233, I2C_BUS3, INA233_E1S_2_ADDR,
	  INA233_CURR_OFFSET, dc_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL,
	  &ina233_init_args[0] },

	{ SENSOR_NUM_1OU_P12V_CURR_A, sensor_dev_ina233, I2C_BUS3, INA233_MAIN_ADDR,
	  INA233_CURR_OFFSET, dc_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL,
	  &ina233_init_args[0] },

	//INA233 PWR
	{ SENSOR_NUM_1OU_E1S_SSD0_P12V_PWR_W, sensor_dev_ina233, I2C_BUS3, INA233_E1S_0_ADDR,
	  INA233_PWR_OFFSET, dc_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL,
	  &ina233_init_args[0] },

	{ SENSOR_NUM_1OU_E1S_SSD1_P12V_PWR, sensor_dev_ina233, I2C_BUS3, INA233_E1S_1_ADDR,
	  INA233_PWR_OFFSET, dc_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL,
	  &ina233_init_args[0] },

	{ SENSOR_NUM_1OU_E1S_SSD2_P12V_PWR, sensor_dev_ina233, I2C_BUS3, INA233_E1S_2_ADDR,
	  INA233_PWR_OFFSET, dc_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL,
	  &ina233_init_args[0] },

	{ SENSOR_NUM_1OU_P12V_PWR_W, sensor_dev_ina233, I2C_BUS3, INA233_MAIN_ADDR,
	  INA233_PWR_OFFSET, dc_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL,
	  &ina233_init_args[0] },
};
sensor_cfg plat_3OU_sensor_config[] = {

	{ SENSOR_NUM_3OU_TEMP, sensor_dev_tmp75, I2C_BUS4, TMP75_TEMP_ADDR, TMP75_TEMP_OFFSET,
	  stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0,
	  SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL, NULL },
	//adc
	{ SENSOR_NUM_3OU_P3V3_STBY_ADC_VOLT_V, sensor_dev_ast_adc, ADC_PORT0, NONE, NONE,
	  stby_access, 2, 1, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0,
	  SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL, &adc_asd_init_args[0] },

	{ SENSOR_NUM_3OU_E1S_SSD0_P3V3_ADC_VOLT_V, sensor_dev_ast_adc, ADC_PORT1, NONE, NONE,
	  dc_access, 2, 1, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0,
	  SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL, &adc_asd_init_args[0] },

	{ SENSOR_NUM_3OU_E1S_SSD1_P3V3_ADC_VOLT_V, sensor_dev_ast_adc, ADC_PORT2, NONE, NONE,
	  dc_access, 2, 1, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0,
	  SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL, &adc_asd_init_args[0] },

	{ SENSOR_NUM_3OU_E1S_SSD2_P3V3_ADC_VOLT_V, sensor_dev_ast_adc, ADC_PORT3, NONE, NONE,
	  dc_access, 2, 1, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0,
	  SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL, &adc_asd_init_args[0] },

	{ SENSOR_NUM_3OU_P1V8_ADC_VOLT_V, sensor_dev_ast_adc, ADC_PORT4, NONE, NONE, dc_access, 1,
	  1, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS,
	  NULL, NULL, NULL, NULL, &adc_asd_init_args[0] },

	{ SENSOR_NUM_3OU_P0V9_ADC_VOLT_V, sensor_dev_ast_adc, ADC_PORT5, NONE, NONE, dc_access, 1,
	  1, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS,
	  NULL, NULL, NULL, NULL, &adc_asd_init_args[0] },

	{ SENSOR_NUM_3OU_P1V2_ADC_VOLT_V, sensor_dev_ast_adc, ADC_PORT6, NONE, NONE, dc_access, 1,
	  1, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS,
	  NULL, NULL, NULL, NULL, &adc_asd_init_args[0] },

	//INA233 VOL
	{ SENSOR_NUM_3OU_E1S_SSD0_P12V_VOLT_V, sensor_dev_ina233, I2C_BUS3, INA233_E1S_0_ADDR,
	  INA233_VOLT_OFFSET, dc_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL,
	  &ina233_init_args[0] },

	{ SENSOR_NUM_3OU_E1S_SSD1_P12V_VOLT_V, sensor_dev_ina233, I2C_BUS3, INA233_E1S_1_ADDR,
	  INA233_VOLT_OFFSET, dc_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL,
	  &ina233_init_args[0] },

	{ SENSOR_NUM_3OU_E1S_SSD2_P12V_VOLT_V, sensor_dev_ina233, I2C_BUS3, INA233_E1S_2_ADDR,
	  INA233_VOLT_OFFSET, dc_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL,
	  &ina233_init_args[0] },

	{ SENSOR_NUM_3OU_P12V_VOLT_V, sensor_dev_ina233, I2C_BUS3, INA233_MAIN_ADDR,
	  INA233_VOLT_OFFSET, dc_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL,
	  &ina233_init_args[0] },

	//INA233 CURR
	{ SENSOR_NUM_3OU_E1S_SSD0_P12V_CURR_A, sensor_dev_ina233, I2C_BUS3, INA233_E1S_0_ADDR,
	  INA233_CURR_OFFSET, dc_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL,
	  &ina233_init_args[0] },

	{ SENSOR_NUM_3OU_E1S_SSD1_P12V_CURR, sensor_dev_ina233, I2C_BUS3, INA233_E1S_1_ADDR,
	  INA233_CURR_OFFSET, dc_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL,
	  &ina233_init_args[0] },

	{ SENSOR_NUM_3OU_E1S_SSD2_P12V_CURR, sensor_dev_ina233, I2C_BUS3, INA233_E1S_2_ADDR,
	  INA233_CURR_OFFSET, dc_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL,
	  &ina233_init_args[0] },

	{ SENSOR_NUM_3OU_P12V_CURR_A, sensor_dev_ina233, I2C_BUS3, INA233_MAIN_ADDR,
	  INA233_CURR_OFFSET, dc_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL,
	  &ina233_init_args[0] },

	//INA233 PWR
	{ SENSOR_NUM_3OU_E1S_SSD0_P12V_PWR_W, sensor_dev_ina233, I2C_BUS3, INA233_E1S_0_ADDR,
	  INA233_PWR_OFFSET, dc_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL,
	  &ina233_init_args[0] },

	{ SENSOR_NUM_3OU_E1S_SSD1_P12V_PWR, sensor_dev_ina233, I2C_BUS3, INA233_E1S_1_ADDR,
	  INA233_PWR_OFFSET, dc_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL,
	  &ina233_init_args[0] },

	{ SENSOR_NUM_3OU_E1S_SSD2_P12V_PWR, sensor_dev_ina233, I2C_BUS3, INA233_E1S_2_ADDR,
	  INA233_PWR_OFFSET, dc_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL,
	  &ina233_init_args[0] },

	{ SENSOR_NUM_3OU_P12V_PWR_W, sensor_dev_ina233, I2C_BUS3, INA233_MAIN_ADDR,
	  INA233_PWR_OFFSET, dc_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL,
	  &ina233_init_args[0] },
};

/*
 * TODO :
 * Identify 1OU or 3OU and set table size
 */

const int SENSOR_CONFIG_SIZE =
	ARRAY_SIZE(plat_1OU_sensor_config); // Use 1OU sesnsor table currently

void load_sensor_config(void)
{
	memcpy(sensor_config, plat_1OU_sensor_config,
	       sizeof(sensor_cfg) * SENSOR_CONFIG_SIZE); // Use 1OU sesnsor table currently
	sensor_config_count = SENSOR_CONFIG_SIZE;
}
